version: '3'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
  backend.com:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/movie_rank_chart
    image: kjb95/movie-rank-chart-backend:1.0
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    tty: true
    restart: always
  frontend.com:
    image: kjb95/movie-rank-chart-frontend:1.0
    ports:
      - "80:80"
    depends_on:
      - backend.com
    tty: true
    restart: always